name: Actualizar Streams HLS

on:
  schedule:
    # Se ejecuta automáticamente cada 5 minutos
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permite ejecución manual desde GitHub

jobs:
  fetch-m3u8:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Obtener archivos M3U8 originales
        run: |
          # Stream 1
          curl -s "https://stream.zeno.fm/idqecp6rhbnvv" -o eradio.m3u8

          # Stream 2 (Agrega aquí otro canal o fuente)
          curl -s "http://181.209.105.115:2525/play/ae/index.m3u8" -o ae.m3u8

          # Stream 3
          curl -s "http://181.209.105.115:2525/play/cronica/index.m3u8" -o cronicatv.m3u8

      - name: Publicar cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add *.m3u8
          git commit -m "Actualizar streams M3U8" || exit 0
          git push
